apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-test-global-tls
  namespace: gateway
spec:
  secretName: wildcard-test-global-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "*.test.global"
